export class Review{

    constructor(
        // Autogenerated.Firebase
        public id: string,
        public placeId: string,
        public title: string,
        public description: string,
        public rating: number,
    ){ }
}